### ISSUE TITLE
图片选择界面的样式是否可以自定义

### ISSUE THREAD

**Issue by zhangGuangFu** [NFLeo/Matisse-Kotlin#10]
图片选择的界面是以圆形的checkbox呈现，可以修改圆形或者去掉圆形复选框吗。 选择单张图片的情况，我想去掉复选框，点击图片后直接进入预览界面或者裁剪界面。谢谢。

**Comment by NFLeo** [comment]
需求1：修改选择框样式
需求2：单选无选择框模式

需求1，后期会考虑支持。
需求2，由于单选可以替换选择，点击直接预览或者裁剪个人感觉也不是很好。后期考虑单选裁剪模式下，右上角确认按钮直接跳转到裁剪。顺利的话今天会发个版到bintrary

**Comment by NFLeo** [comment]
看了下  单选裁剪本来就是直接进入裁剪的
