### ISSUE TITLE
图片裁剪会拉伸变形

### ISSUE THREAD

**Issue by Carlos2927** [NFLeo/Matisse-Kotlin#11]
![图片](https://user-images.githubusercontent.com/12493233/67143899-1193ca00-f2a3-11e9-9928-ddb7c1bbd435.png)

**Comment by Carlos2927** [comment]
![图片](https://user-images.githubusercontent.com/12493233/67143922-443dc280-f2a3-11e9-8cc7-931265148441.png)
![图片](https://user-images.githubusercontent.com/12493233/67143929-591a5600-f2a3-11e9-9fbb-32818d2d33c4.png)

**Comment by NFLeo** [comment]
已经修复了 目前的做法是去掉了cropOutPutX、cropOutPutY，直接读取裁剪框作为图片大小
