### ISSUE TITLE
圆形裁剪还是有问题呢

### ISSUE THREAD

**Issue by creativityingenuity** [NFLeo/Matisse-Kotlin#14]
裁剪后 使用fresco 或者 glide 加载 
使用的是imageview或者fresco自带的view  
样式是圆形头像框
加载出现偏移
![图片](https://user-images.githubusercontent.com/12170093/68283410-78dcb700-00b6-11ea-9ad6-fb0c6517c6d3.png)

**Comment by NFLeo** [comment]
好的 先收录了。你手上设备是什么型号？我身边这几个手机都试了一下还没出现你这种情况

**Comment by creativityingenuity** [comment]
三星s8
您好 ，可以设置网络图片墙点击预览吗   找了半天了

**Comment by creativityingenuity** [comment]
![图片](https://user-images.githubusercontent.com/12170093/68388803-69d03480-019c-11ea-9199-eed68f8247f3.png)
album item 还有一些参数搞不明白

**Comment by NFLeo** [comment]
网络图片墙？不大明白您的意思。这个库就是获取设备上图片，不涉及到网络图片


关于Item、Album内参数，你可以看Item.kt，Album.kt里面的valueOf方法，其实就是对Cursor的一个转换

**Comment by creativityingenuity** [comment]
就是选择完多张照片然后上传，上传完成列表显示，而且可以点击进行预览  就像在选择照片时，点击照片预览效果一样，但是这个是url地址，是这样的一个需求

**Comment by NFLeo** [comment]
哦哦 这个是库以外的东西，不做在库里面的。也许以后我会单独把预览抽出来，但是近段时间不会。裁剪问题 你要不换个设备试试看，我这也找找s8

**Comment by creativityingenuity** [comment]
兄弟 可以留个联系方式吗  在用这个库 有问题请教

**Comment by NFLeo** [comment]
裁剪的问题我发现了，等周一解决了就发个小版本  973555610@qq.com 我邮箱

**Comment by NFLeo** [comment]
已经修复了  代码提交了 等明天发布2.0.1
