### ISSUE TITLE
列表状态单选没办法换照片，预览状态系统无视数量限制

### ISSUE THREAD

**Issue by pomyPeng** [NFLeo/Matisse-Kotlin#17]
![Uploading Screenshot_20191210-183419_My Application.jpg…]()

![Screenshot_20191210-183349_My Application](https://user-images.githubusercontent.com/57423239/70524604-80ddba00-1b80-11ea-97d6-c63b705893ec.jpg)

**Comment by NFLeo** [comment]
这个demo只是个很粗糙的demo。测试的时候都是挨个api测试的，有些api混用可能会有问题。你可以检查一下你的参数设置。demo简单使用是没问题的，如果有问题，可以看下是不是最新的代码
