### ISSUE TITLE
逻辑问题

### ISSUE THREAD

**Issue by pomyPeng** [NFLeo/Matisse-Kotlin#18]
MatisseActivity主预览界面只能点击一张图片，点击第二章或取消会弹出”你只能选择0张图片“吐司，大图界面会无视设定的最大选择数量，比如设定了1张大图点到10多张这样子......

**Comment by NFLeo** [comment]
![image](https://user-images.githubusercontent.com/13409676/70800257-b8e63680-1de6-11ea-8063-acc1b01296be.png)麻烦看看这几个参数你设置的多少

**Comment by pomyPeng** [comment]
谢谢，我mediatype设置错了，请问一下选择后能跳转在其他activity吗

**Comment by NFLeo** [comment]
跳其他activity是什么意思？

**Comment by pomyPeng** [comment]
选择完照片后带着返回值去一个新的activity

**Comment by NFLeo** [comment]
如果关闭裁剪的话，选择图片后点击确定，会在上一层的onActivityForResult回调中拿到选中结果，这个时候去另一个新的activity

**Comment by pomyPeng** [comment]
感谢
