### ISSUE TITLE
单选切换提示

### ISSUE THREAD

**Issue by jmessage** [NFLeo/Matisse-Kotlin#19]
图片单选，然后在选中一张图片，在选择另一个替换，提示最多只能选择0个图片，算中清除了，右上角确定数量显示是(1)

**Comment by NFLeo** [comment]
之前的demo是不完善的，我现在也不记得是怎么样的。这种情况应该是你设置了混合选择模式。单选情况下，只能选择单一选择模式。你确认一下，库没问题的，应该是demo的问题
