### ISSUE TITLE
相机拍照，但是不进行裁剪，返回相册数据列表没有刷新

### ISSUE THREAD

**Issue by xiedaimayeyaolang** [NFLeo/Matisse-Kotlin#21]
需要设置其他参数么？我的设置如下

                Matisse.Companion.from(this)
                        .choose(MimeTypeManager.Companion.ofImage())
                    .countable(false)
                    .capture(true)
                    .isCrop(false)
                    .maxSelectable(1)
                    .theme(R.style.Matisse_Dark)
                    .captureStrategy(
                           new CaptureStrategy(
                                    true,
                                    Platform.INSTANCE.getPackageName(MNTCameraActivity.this)+".utils.provider.MyFileProvider",
                                    "discern"
                            )
                    )
                    .thumbnailScale(0.8f)
                        .setIsInnerCompress(false)
                    .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                    .imageEngine(new GlideEngine())
                        .forResult(ConstValue.REQUEST_CODE_CHOOSE);

**Comment by NFLeo** [comment]
设置是这样没问题，目前部分设备，第一次拍照刷新不显示，第二次才行。这是个bug，暂时还没空解决

**Comment by NFLeo** [comment]
刚刚试着改了一下，这个bug好像修复了，你那里看看还有没有问题。发布了2.0.3版本

**Comment by xiedaimayeyaolang** [comment]
> 刚刚试着改了一下，这个bug好像修复了，你那里看看还有没有问题。发布了2.0.3版本

试了一下，还是不行，华为mata20，安卓10系统，其他的手机没试

**Comment by NFLeo** [comment]
我们现在还没Android 10的设备，也没针对Android 10做太多测试。可能年后会申请到Android 10的设备。这个bug只能不好意思了额

**Comment by NFLeo** [comment]
2.0.4 已经修复了
