### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by RUANHAOANDROID** [NFLeo/Matisse-Kotlin#23]
02-02 15:08:30.600 369-392/? E/ActivityManager: ANR in com.unistrong.mapoffline (com.unistrong.mapoffline/com.matisse.ui.activity.matisse.MatisseActivity)
    PID: 1866
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 4.  Wait queue head age: 5856.9ms.)
    Load: 0.76 / 0.23 / 0.12
    CPU usage from 50882ms to 0ms ago:
      6.2% 369/system_server: 6.2% user + 0% kernel / faults: 4392 minor 303 major
      0.2% 222/adbd: 0% user + 0.2% kernel / faults: 703 minor
      0% 880/com.netease.nemu_vapi_android.nemu: 0% user + 0% kernel / faults: 1801 minor 54 major
      0% 25/kswapd0
    : 0% user + 0% kernel
      0% 904/com.mumu.launcher: 0% user + 0% kernel / faults: 603 minor 60 major
      0% 6/kworker/u2:0: 0% user + 0% kernel
      0.3% 227/local_gps: 0.2% user + 0% kernel
      0% 1517/com.android.packageinstaller: 0% user + 0% kernel / faults: 821 minor 18 major
      0% 105/logd: 0% user + 0% kernel / faults: 40 minor 2 major
      0% 225/surfaceflinger: 0% user + 0% kernel / faults: 3 minor 2 major
      0.1% 1075/com.mumu.store: 0.1% user + 0% kernel / faults: 1401 minor 28 major
      0% 1758/logcat: 0% user + 0% kernel
      0% 90/jbd2/sdb3-8: 0% user + 0% kernel
      0.1% 849/com.tencent.mobileqq:MSF: 0% user + 0% kernel / faults: 80 minor 21 major
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0% 646/sdcard: 0% user + 0% kernel / faults: 3 minor 2 major
      0% 653/com.android.systemui: 0% user + 0% kernel / faults: 137 minor 13 major
      0% 66/kworker/0:1H: 0% user + 0% kernel
      0% 1651/com.android.phone: 0% user + 0% kernel / faults: 139 minor 22 major
      0% 7/rcu_preempt: 0% user + 0% kernel
      0% 10/rcuop/0: 0% user + 0% kernel
      0% 224/servicemanager: 0% user + 0% kernel / faults: 2 minor 1 major
      0% 1172/com.mumu.acc: 0% user + 0% kernel / faults: 226 minor 22 major
      0% 1238/com.android.keychain: 0% user + 0% kernel / faults: 459 minor 3 major
      0% 223/lmkd: 0% user + 0% kernel / faults: 1 major
      0% 226/vinput: 0% user + 0% kernel / faults: 2 minor 1 major
      0% 240/netd: 0% user + 0% kernel / faults: 60 minor 4 major
      0% 247/zygote: 0% user + 0% kernel / faults: 1208 minor
      0% 251/opengl-gc: 0% user + 0% kernel
      0% 921/android.process.media: 0% user + 0% kernel / faults: 601 minor 7 major
      0% 1599/com.android.defcontainer: 0% user + 0% kernel / faults: 581 minor 1 major
      0% 1621/com.android.settings:superuser: 0% user + 0% kernel / faults: 718 minor 24 major
     +0% 1866/com.unistrong.mapoffline: 0% user + 0% kernel
    94% TOTAL: 86% user + 6.6% kernel + 0.6% iowait + 0.2% irq + 0.9% softirq
    CPU usage from 826ms to 1327ms later:
      99% 1866/com.unistrong.mapoffline: 97% user + 1.9% kernel / faults: 2137 minor
        85% 1866/rong.mapoffline: 85% user + 0% kernel
        13% 1877/HeapTaskDaemon: 11% user + 1.9% kernel
    100% TOTAL: 98% user + 2% kernel

**Comment by RUANHAOANDROID** [comment]
`02-02 15:08:30.600 369-392/? E/ActivityManager: ANR in com.unistrong.mapoffline (com.unistrong.mapoffline/com.matisse.ui.activity.matisse.MatisseActivity)
    PID: 1866
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 4.  Wait queue head age: 5856.9ms.)
    Load: 0.76 / 0.23 / 0.12
    CPU usage from 50882ms to 0ms ago:
      6.2% 369/system_server: 6.2% user + 0% kernel / faults: 4392 minor 303 major
      0.2% 222/adbd: 0% user + 0.2% kernel / faults: 703 minor
      0% 880/com.netease.nemu_vapi_android.nemu: 0% user + 0% kernel / faults: 1801 minor 54 major
      0% 25/kswapd0
    : 0% user + 0% kernel
      0% 904/com.mumu.launcher: 0% user + 0% kernel / faults: 603 minor 60 major
      0% 6/kworker/u2:0: 0% user + 0% kernel
      0.3% 227/local_gps: 0.2% user + 0% kernel
      0% 1517/com.android.packageinstaller: 0% user + 0% kernel / faults: 821 minor 18 major
      0% 105/logd: 0% user + 0% kernel / faults: 40 minor 2 major
      0% 225/surfaceflinger: 0% user + 0% kernel / faults: 3 minor 2 major
      0.1% 1075/com.mumu.store: 0.1% user + 0% kernel / faults: 1401 minor 28 major
      0% 1758/logcat: 0% user + 0% kernel
      0% 90/jbd2/sdb3-8: 0% user + 0% kernel
      0.1% 849/com.tencent.mobileqq:MSF: 0% user + 0% kernel / faults: 80 minor 21 major
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0% 646/sdcard: 0% user + 0% kernel / faults: 3 minor 2 major
      0% 653/com.android.systemui: 0% user + 0% kernel / faults: 137 minor 13 major
      0% 66/kworker/0:1H: 0% user + 0% kernel
      0% 1651/com.android.phone: 0% user + 0% kernel / faults: 139 minor 22 major
      0% 7/rcu_preempt: 0% user + 0% kernel
      0% 10/rcuop/0: 0% user + 0% kernel
      0% 224/servicemanager: 0% user + 0% kernel / faults: 2 minor 1 major
      0% 1172/com.mumu.acc: 0% user + 0% kernel / faults: 226 minor 22 major
      0% 1238/com.android.keychain: 0% user + 0% kernel / faults: 459 minor 3 major
      0% 223/lmkd: 0% user + 0% kernel / faults: 1 major
      0% 226/vinput: 0% user + 0% kernel / faults: 2 minor 1 major
      0% 240/netd: 0% user + 0% kernel / faults: 60 minor 4 major
      0% 247/zygote: 0% user + 0% kernel / faults: 1208 minor
      0% 251/opengl-gc: 0% user + 0% kernel
      0% 921/android.process.media: 0% user + 0% kernel / faults: 601 minor 7 major
      0% 1599/com.android.defcontainer: 0% user + 0% kernel / faults: 581 minor 1 major
      0% 1621/com.android.settings:superuser: 0% user + 0% kernel / faults: 718 minor 24 major
     +0% 1866/com.unistrong.mapoffline: 0% user + 0% kernel
    94% TOTAL: 86% user + 6.6% kernel + 0.6% iowait + 0.2% irq + 0.9% softirq
    CPU usage from 826ms to 1327ms later:
      99% 1866/com.unistrong.mapoffline: 97% user + 1.9% kernel / faults: 2137 minor
        85% 1866/rong.mapoffline: 85% user + 0% kernel
        13% 1877/HeapTaskDaemon: 11% user + 1.9% kernel
    100% TOTAL: 98% user + 2% kernel`

**Comment by NFLeo** [comment]
v2.1已经修复了  不过暂时还没传到bintray
