### ISSUE TITLE
不支持视频类型

### ISSUE THREAD

**Issue by SpielbergGao** [NFLeo/Matisse-Kotlin#4]
在选择视频时提示不支持文件类型，选择视频是禁止该操作或是有其他开启的方法？

**Comment by NFLeo** [comment]
确实有个bug，媒体类型配置时，没把mp4格式加上去。现在已经加了。
我已经上传了一个androidx的分支上去，修复了这个问题，这个分支里面有个aar，不确定你能不能用。改动地方主要是MimeType.kt类改了下面这一段：（mp4是新加的）
    MP4 {
        override fun getValue() = MimeTypeManager.arraySetOf("m4v","mp4")
        override fun getKey() = "video/mp4"
        override fun initEnum() = MimeTypeManager(getKey(), getValue())
    }

**Comment by SpielbergGao** [comment]
感谢，我修复一下。
