### ISSUE TITLE
视频与图片选择限制

### ISSUE THREAD

**Issue by SpielbergGao** [NFLeo/Matisse-Kotlin#5]
目前的情景是：
1. 视频设置最大选取 1
2. 图片设置最大选取 9
问题：
先选择图片，然后可以选择多个视频，此时图片限制和视频限制逻辑没有触发。

**Comment by NFLeo** [comment]
视频和图片分开设置？

**Comment by SpielbergGao** [comment]
使用  maxSelectablePerMediaType(9,1) 这个函数，showSingleMediaType(false), choose(MimeTypeManager.ofAll()true),这样子可以多选，但实际可以选择的数量大于限制的数量，如果showSingleMediaType(true),如果以选择俩张图片后在选择一张图片，会提示图片与视频不能同时选择。这个地方的逻辑，需要修改哪里？我修改测试没问题后提个 RP。

**Comment by NFLeo** [comment]
对 目前确实有这个问题，现在代码太乱了，是打算重构的，最近有点忙，我尽快改吧，你也可以提上来

**Comment by SpielbergGao** [comment]
我单独将视频与图片的设置方式分离了。我在 add 添加的时候对类型设置的地方注释了
                COLLECTION_IMAGE, COLLECTION_VIDEO -> {
                    if (item.isVideo() || item.isImage()) {
                        mCollectionType = COLLECTION_MIXED
                    }
                }
这段话，分别进行设计，我发现这段话会导致类型识别错误，当选择图片时，俩张可以第三张出现不能同时选择视屏与图片的问题。我取消了 COLLECTION_MIXED 类型的设置，目前是没有问题 的，我在整理前后的逻辑。

**Comment by NFLeo** [comment]
这个问题已经修复了  1.2.0可用

**Comment by SpielbergGao** [comment]
收到您的回复

NFLeo <notifications@github.com> 于2019年10月18日周五 下午1:02写道：
