### ISSUE TITLE
能否支持Android 10?

### ISSUE THREAD

**Issue by Carlos2927** [NFLeo/Matisse-Kotlin#6]
![图片](https://user-images.githubusercontent.com/12493233/64469787-c1d1c700-d16a-11e9-871f-efd7fd67fd60.png)

**Comment by NFLeo** [comment]
我用模拟器试了，没复现这个问题

**Comment by Carlos2927** [comment]
可能模拟器测试不出来 但是真机测试是有的 Matisse那边也有人提交了同样的[issue](https://github.com/zhihu/Matisse/issues/659)

**Comment by NFLeo** [comment]
嗯嗯 你可以去那里提个issue，他们应该能很快解决，目前公司没安卓10设备，不好复现

**Comment by phantomVK** [comment]
用Android 10的Android Studio模拟器可以复现. 
Same error in Android 10 emulator using Android Studio.

**Comment by NFLeo** [comment]
已经按官网的方式适配了 1.2.3版本可用
